#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    external_bar                 all:30:30       \
    menubar_opacity              1.0            \
    mouse_follows_focus          on      \
    focus_follows_mouse          autofocus      \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                off            \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    window_gap			 10		\
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 on             \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

#borders active_color=0xffFFFFFF inactive_color=0xff86FFA2 width=8.0 &
borders active_color="glow(0xffFFFFFF)" inactive_color="gradient(top_left=0xffFF6F61,bottom_right=0xff6A1B9A)" width=8.0

# Query the current spaces
# yabai -m query --spaces

yabai -m space 1 --label brave
yabai -m space 2 --label Slack
yabai -m space 3 --label brave2
yabai -m space 4 --label iTerm2
yabai -m space 5 --label Spotify
yabai -m space 6 --label lens
yabai -m space 7 --label code

yabai -m rule --add app="^Brave$" space=brave
yabai -m rule --add app="^Slack$" space=Slack
yabai -m rule --add app="^iTerm2$" space=iTerm2
yabai -m rule --add app="^Spotify$" space=Spotify
yabai -m rule --add app="^Lens$" space=lens
yabai -m rule --add app="^Code$" space=code


echo "yabai configuration loaded.."
