#!/usr/bin/env zsh

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"
SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

# ── Bottom Bar Setup ───────────────────────────────────────────────
bottom_bar --bar \
    height=30 \
    color=0xcc1F2331 \
    corner_radius=15 \
    margin=5 \
    y_offset=1 \
    sticky=on \
    padding_left=5 \
    padding_right=5 \
    position=bottom \
    display=all

# ── Defaults ────────────────────────────────────────────────────────
bottom_bar --default \
    background.color=0x66494d64 \
    background.corner_radius=13 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$FONT_FACE:Medium:12.0" \
    icon.padding_left=8 \
    icon.padding_right=8 \
    label.font="$FONT_FACE:Medium:10.0" \
    label.color=0xffcad3f5 \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=8

# ── Weather ─────────────────────────────────────────────────────────
bottom_bar --add item temperature left \
    --set temperature \
    icon= \
    icon.color=0xfff5bde6 \
    icon.font="$FONT_FACE:Bold:12.0" \
    update_freq=1800 \
    script="$PLUGIN_SHARED_DIR/temperature.sh" \
    --subscribe temperature system_woke

bottom_bar --add item weather left \
    --set weather \
    icon="" \
    icon.color=0xfff5bde6 \
    icon.font="$FONT_FACE:Bold:12.0" \
    update_freq=1800 \
    script="$PLUGIN_SHARED_DIR/weather.sh" \
    --subscribe weather system_woke

bottom_bar --add item wind left \
    --set wind \
    icon="" \
    icon.color=0xfff5bde6 \
    icon.font="$FONT_FACE:Bold:12.0" \
    update_freq=1800 \
    script="$PLUGIN_SHARED_DIR/wind_info.sh" \
    --subscribe wind system_woke

# ── Final Update ────────────────────────────────────────────────────
bottom_bar --update
